### PR TITLE
Add browser version to test parameter

### PR DESCRIPTION
**Pull request by BorisOsipov**
- Add browser version to test parameter
- Properly set thread label for cucumber version

### CODE REVIEW

**Comment by BorisOsipov** [comment]
Fixes https://github.com/webdriverio-boneyard/wdio-allure-reporter/issues/131

**Comment by osmolyar** [comment]
Hi @BorisOsipov , (@christian-bromann), thank you for this fix, it is working but when you run tests on IE10 and IE11, it outputs 3 results for each test- 1 for 'internet explorer-10', 1 for 'internet explorer-11' and one for 'internet explorer':
image

**Comment by BorisOsipov** [comment]
@osmolyar do you clear allure-results folder? this fix can't add additional tests anyway

**Comment by osmolyar** [comment]
Ah, that must be it; thanks

**Comment by osmolyar** [comment]
Yes, that was it, thank you.

**Comment by tudor-belea** [comment]
> Hi @BorisOsipov , thank you for this fix, it is working, but when you run tests on IE10 and IE11, it outputs 3 results for each test instead of two- 1 for 'internet explorer-10', 1 for 'internet explorer-11' and one for 'internet explorer':
> image

Hi, @osmolyar ,

I'm having the exact same issue, I want to run the same  protractor test 2 times using a configuration file in which I specify multiCapabilities. The test runs successfully against the 2 browsers but the allure report that I generate after that only includes one of the runs. I would like to be able to include in the report the exact same argument as you did in the above example, the same test step twice with the browser name specified next to it. Can you please advise how I can achieve that? I've been struggling for a couple of days now & with no success.

**Comment by osmolyar** [comment]
Do you have the latest allure version?  It outputs the browser name next to the test automatically.

**Comment by tudor-belea** [comment]
I believe so, although I was using jasmine-allure-reporter to generate the test output for allure. Should I switch to using wdio-allure-reporter instead? I am writing tests using protractor & node.js. Would this work for my setup as well? I am trying to generate an allure report based on a conf file run that looks like this: 

exports.config = {
    SELENIUM_PROMISE_MANAGER: protractorConf.SELENIUM_PROMISE_MANAGER,
    directConnect: true,
    multiCapabilities: [{
        browserName: 'firefox',
        'moz:firefoxOptions': {
            binary: "C:/Program Files/Mozilla Firefox/firefox.exe",
        },
        'maxInstances': 1
    },{
        browserName: 'chrome',
        'chromeOptions': {
            args: ['--window-size=375,812', 'disable-infobars'],
            mobileEmulation: {
                deviceName: 'iPhone X'
            },
        },
        'maxInstances': 1
    }],

**Comment by osmolyar** [comment]
Yes, it's wdio-allure-reporter that was changed to support this, I believe.

**Pull request merged**
